title: "Justin Kin Jun Hew"
author: "Justin Kin Jun Hew"
description: "Research Software Engineer at ACCESS-NRI and computational physics researcher"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "research.md"}
  - {file: "publications.md"}
  - {file: "about.md", title: "About"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: ORCID, icon: link, url: "https://orcid.org/0000-0002-5238-6115"}
  - {title: Github, icon: github, url: "https://github.com/justinh2002"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Justin-Kin-Jun-Hew"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
